services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management UI
    networks:
      - trackpak-network

  api-gateway:
    image: trackpak-apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5056:8080" # API Gateway port
    depends_on:
      - company-service
      - location-service
      - order-service
      - user-service
      - tracking-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OCELOT_CONFIGURATION=ocelot.json # Ocelot config file
    networks:
      - trackpak-network
  
  company-service:
    image: trackpak-companyservice
    build:
      context: .
      dockerfile: CompanyService.Api/Dockerfile
    depends_on:
      - rabbitmq
      - company-db
    deploy:
      replicas: 2
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=company-db;Port=5432;Database=trackpak-companydb;Username=developer;Password=trackPak_dev_password
    networks:
      - trackpak-network
    
  location-service:
      image: trackpak-locationservice
      build:
        context: .
        dockerfile: LocationService.Api/Dockerfile
      depends_on:
        - rabbitmq
        - location-db
      deploy:
        replicas: 2
      restart: unless-stopped
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__Postgres=Host=location-db;Port=5432;Database=trackpak-locationdb;Username=developer;Password=trackPak_dev_password
      networks:
        - trackpak-network
    
  order-service:
      image: trackpak-orderservice
      build:
        context: .
        dockerfile: OrderService.Api/Dockerfile
      depends_on:
        - rabbitmq
        - order-db
      deploy:
        replicas: 2
      restart: unless-stopped
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__Postgres=Host=order-db;Port=5432;Database=trackpak-orderdb;Username=developer;Password=trackPak_dev_password
      networks:
        - trackpak-network
    
  user-service:
      image: trackpak-userservice
      build:
        context: .
        dockerfile: UserService.Api/Dockerfile
      depends_on:
        - rabbitmq
        - user-db
      deploy:
        replicas: 2
      restart: unless-stopped
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__Postgres=Host=user-db;Port=5432;Database=trackpak-userdb;Username=developer;Password=trackPak_dev_password
      networks:
        - trackpak-network
      
  tracking-service:
    image: trackpak-trackingservice
    build:
      context: .
      dockerfile: TrackingService.Api/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - trackpak-network
        
  company-db:
    image: postgres:15
    container_name: company-db
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: trackPak_dev_password
      POSTGRES_DB: trackpak-companydb
    ports:
      - "5432:5432"
    volumes:
      - company-db-data:/var/lib/postgresql/data
    networks:
      - trackpak-network
      
  location-db:
    image: postgres:15
    container_name: location-db
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: trackPak_dev_password
      POSTGRES_DB: trackpak-locationdb
    ports:
      - "5433:5432"
    volumes:
      - location-db-data:/var/lib/postgresql/data
    networks:
      - trackpak-network
    
  order-db:
    image: postgres:15
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: trackPak_dev_password
      POSTGRES_DB: trackpak-orderdb
    ports:
      - "5434:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - trackpak-network
  
  user-db:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: trackPak_dev_password
      POSTGRES_DB: trackpak-userdb
    ports:
      - "5435:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - trackpak-network
        
  

networks:
  trackpak-network:
    driver: bridge 
    
volumes:
  company-db-data:
  location-db-data:
  order-db-data:
  user-db-data: