@UserService.Api_HostAddress = http://localhost:5218

GET  http://localhost:5218/user/7988f0f8-c8da-4676-ba62-cfd45f010446
Accept: application/json

###


POST http://localhost:5218/user/
Content-Type: application/json
Accept: application/json

{
  "firstName": "Test",
  "lastName": "Doe",
  "phoneNumber": "20111022",
  "email": "john@doe.dk"
}